package Av_Modules.Consts

val NITRO_UI_MODULES = listOf(
  "about",
  "antiRansomware",
  "antiSpam",
  "antiTrack",
  "batterySaver",
  "browserCleanup",
  "browserExtensions",
  "compatibility",
  "core",
  "darkWebMonitor",
  "dashboard",
  "dataSafe",
  "dataShredder",
  "debug",
  "doNotDisturb",
  "driverUpdater",
  "feedbackForm",
  "firewall",
  "fusion",
  "help",
  "i18n",
  "libs",
  "mainLayout",
  "map",
  "myLicenses",
  "napi",
  "napiAdapter",
  "napiExtensions",
  "network",
  "notifications",
  "pam",
  "pap",
  "passwordProtection",
  "plugins",
  "ractiveAdapter",
  "ractiveComponents",
  "ras",
  "recommendations",
  "rescueDisk",
  "sandbox",
  "scans",
  "secureBrowser",
  "secureDns",
  "secureLine",
  "sensitiveData",
  "settings",
  "shields",
  "smartHome",
  "smartScan",
  "software",
  "svelteComponents",
  "system",
  "tray",
  "tuneup",
  "virusChest",
  "webCam"
)

// modules that have 3rdPartyLibs.json in their artifacts
val MODULES_WITH_3RD_PARTY_LIBS = listOf("kin", "nitro-ui-lib-localization", "spawn") + NITRO_UI_MODULES
